### ISSUE TITLE
Chained "through" associations break ar_lazy_preload

### ISSUE THREAD

**Issue by nattfodd** [DmitryTsepelev/ar_lazy_preload#30]
Hi. Thanks for the wonderful gem! I faced the following issue by just plugging the gem into my project that has chained `has_many through` association:

```ruby
class Employee
  belongs_to :company
  has_many :products, foreign_key: 'created_by_id'
end

class Company
  has_many :employees
  has_many :products, through: :employees
end

class Subproduct
  belongs_to :product
end

class ChannelSubproduct
  belongs_to :subproduct
end

class ChannelProduct
  has_many :channel_subproducts
  has_many :subproducts, through: :channel_subproducts
  has_many :products, -> { uniq }, through: :subproducts
end

class Product
  has_many :subproducts
  has_many :channel_subproducts, through: :subproducts
  has_many :channel_products, through: :channel_subproducts

  belongs_to :created_by, class_name: 'Employee'
end
```

When I try to call `Company.first.products`, the gem fails here:

```log
NoMethodError: undefined method `klass' for nil:NilClass
/bundler/gems/rails-6f310f798eeb/activerecord/lib/active_record/reflection.rb:671:in `source_reflection'
/bundler/gems/rails-6f310f798eeb/activerecord/lib/active_record/reflection.rb:883:in `derive_class_name'
/bundler/gems/rails-6f310f798eeb/activerecord/lib/active_record/reflection.rb:157:in `class_name'
/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/merger.rb:31:in `block in reflect_and_merge_lazy_preloads'
/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/merger.rb:30:in `each'
/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/merger.rb:30:in `find'
/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/merger.rb:30:in `reflect_and_merge_lazy_preloads'
/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/merger.rb:15:in `merge'
```

I believe this is because the nested `through` association has `delegate_reflection` instead (`assoc.class_name` - fails, `assoc.delegate_reflection.class_name` - works):

```
[2] DEVELOPMENT(#<ActiveRecord::Relation::Merger>)> assoc = relation.klass.reflect_on_all_associations.find { |a| !a.class_name rescue a }
=> #<ActiveRecord::Reflection::ThroughReflection:0x00007fb03bdc38e8
 @delegate_reflection=
  #<ActiveRecord::Reflection::HasManyReflection:0x00007fb03bdc3b40
   @active_record=
    Product(...),
   @association_scope_cache={},
   @automatic_inverse_of=nil,
   @constructable=true,
   @foreign_type="channel_products_type",
   @klass=nil,
   @name=:channel_products,
   @options={:through=>:channel_sellables},
   @plural_name="channel_products",
   @scope=nil,
   @scope_lock=#<Thread::Mutex:0x00007fb03bdc3910>,
   @type=nil>,
 @klass=nil,
 @source_reflection_name=nil>
```

`Rails 4.2.10` / `Ruby 2.5.5`

Hope it helps!

**Comment by DmitryTsepelev** [comment]
Hi @nattfodd, thanks for catching that! I'll try to investigate later this week or will be glad to take a look at the PR if you want to give it a shot 🙂

**Comment by nattfodd** [comment]
Sorry for creating this one. I've started digging deeper and found out that in fact it was because of "dead" associations living in the model - there was a dead association`has_many :foo, through: :bar` when there were no `has_many :bar` defined.

The error message was quite misleading, but It definetely not the issue of the `ar_lazy_preload`.

Another thing I've spotted is so it has something weird with `bullet 6.1`, running into circular dependency loop, accessing literally any association:

```
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
```

Since bullet is not running on production, this issue is not that critical. I'll create a separate issue for that.
