### ISSUE TITLE
Conflict with Bullet gem

### ISSUE THREAD

**Issue by nattfodd** [DmitryTsepelev/ar_lazy_preload#31]
Having both `ar_lazy_preload` and `bullet` gems in the project, it ends up in a circular dependency when you try to load any association:

```
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/bundler/gems/ar_lazy_preload-e7fa4004e70c/lib/ar_lazy_preload/active_record/association.rb:8:in `load_target'
/Users/nattfodd/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/bullet-6.1.0/lib/bullet/active_record42.rb:165:in `load_target'
```

I'm not sure wether it should be fixed in bullet or here, had to create the issue somewhere at least:

Bullet patches `load_target` this way:
https://github.com/flyerhzm/bullet/blob/master/lib/bullet/active_record42.rb#L163-L165

ArLazyPreload patches `load_target` this way:
https://github.com/DmitryTsepelev/ar_lazy_preload/blob/master/lib/ar_lazy_preload/active_record/association.rb#L6-L9

**Comment by DmitryTsepelev** [comment]
The problem is that _ar_lazy_preload_ uses `prepend` to patch the `Association` behaviour, while _bullet_ uses `alias_method` and these two metaprogramming tricks do not play well together. I've found an [article](https://blog.newrelic.com/engineering/ruby-agent-module-prepend-alias-method-chains/) explaining exactly the same pattern and the general suggestion is to "migrate everything to use a single metaprogramming pattern". Looks like _bullet_ switched to `prepend` [since ActiveRecord 5](https://github.com/flyerhzm/bullet/blob/master/lib/bullet/active_record5.rb) too.

Unfortunately, I do not see a proper solution here, because such a conflict can appear in any time in future, no matter what (`prepend` or `alias_method`) will be used 🤔
