### ISSUE TITLE
`Stack level is too deep` error when `owner` attribute used in model

### ISSUE THREAD

**Issue by RuslanKhabibullin** [DmitryTsepelev/ar_lazy_preload#49]
Model example:
```
require_dependency 'board'

class Board
  class Member < ::ApplicationRecord
    belongs_to :board
    belongs_to :user

    ADMIN_ROLES = %i[owner admin].freeze

    scope :admins, -> { where(role: ADMIN_ROLES) }

    enum role: { owner: 0, admin: 1, contributor: 2 }
  end
end
```

Error example:

```
/home/ruslan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ar_lazy_preload-0.6.1/lib/ar_lazy_preload/active_record/association_relation.rb:13:in `lazy_preload_context'
/home/ruslan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ar_lazy_preload-0.6.1/lib/ar_lazy_preload/active_record/association_relation.rb:13:in `lazy_preload_context'
/home/ruslan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ar_lazy_preload-0.6.1/lib/ar_lazy_preload/active_record/association_relation.rb:13:in `lazy_preload_context'
/home/ruslan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ar_lazy_preload-0.6.1/lib/ar_lazy_preload/active_record/association_relation.rb:13:in `lazy_preload_context'
/home/ruslan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ar_lazy_preload-0.6.1/lib/ar_lazy_preload/active_record/association_relation.rb:13:in `lazy_preload_context'
/home/ruslan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ar_lazy_preload-0.6.1/lib/ar_lazy_preload/active_record/association_relation.rb:13:in `lazy_preload_context'
/home/ruslan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ar_lazy_preload-0.6.1/lib/ar_lazy_preload/active_record/association_relation.rb:13:in `lazy_preload_context'
/home/ruslan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ar_lazy_preload-0.6.1/lib/ar_lazy_preload/active_record/association_relation.rb:13:in `lazy_preload_context'
/home/ruslan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ar_lazy_preload-0.6.1/lib/ar_lazy_preload/active_record/association_relation.rb:13:in `lazy_preload_context'
/home/ruslan/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/ar_lazy_preload-0.6.1/lib/ar_lazy_preload/active_record/association_relation.rb:13:in `lazy_preload_context'
```

**Comment by RuslanKhabibullin** [comment]
Probably can be fixed by adding the next line:

```
delegate :owner, :reflection, to: :proxy_association, prefix: true
 ```

**Comment by RuslanKhabibullin** [comment]
Also, PR is here if needed: https://github.com/DmitryTsepelev/ar_lazy_preload/pull/50. The issue was fixed for me :)
